import SideMenu from '../components/Dashboard/SideMenu'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function dashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row">
          <div className="basis-[20%]"><SideMenu /></div>
          <div className="basis-[80%] border-dotted border-red-600">{children}</div>
        </div>
      </body>
    </html>
  )
}
